server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: mappings
  health:
    ldap:
      enabled: false
spring:
  data:
    neo4j:
      uri: bolt://localhost
      username: networkManager
      password: appPassword
      embedded:
        enabled: false

