server:
  port: 8090
management:
  health:
    ldap:
      enabled: false
  endpoints:
    web:
      cors:
        allowed-headers: Authorization
        allowed-origins: http://localhost:8080
        allowed-methods: GET", POST, PUT, PATCH, DELETE
        exposed-headers: Authorization
spring:
  data:
    neo4j:
      uri: bolt://localhost
      username: networkManager
      password: appPassword
      embedded:
        enabled: false
  ldap:
    url: ldaps://127.0.0.1:636/
    username: anonymous
    baseDn: ou=staff,o=fis

