server:
  port: 8090
management:
  health:
    ldap:
      enabled: false
spring:
  data:
    neo4j:
      uri: bolt://localhost
      username: networkManager
      password: appPassword
      embedded:
        enabled: false
  ldap:
    url: ldaps://127.0.0.1:636/
    username: anonymous
    baseDn: ou=2014,o=fis

